# Generated by Django 4.2 on 2024-06-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_personne_pass1_personne_pass_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personne',
            old_name='firstname',
            new_name='Nom',
        ),
        migrations.RenameField(
            model_name='personne',
            old_name='lastname',
            new_name='Prenom',
        ),
    ]
